### ISSUE TITLE
ЛР 3

### ISSUE THREAD

**Issue by alexandr-kaa** [Gibadullina-Darina/OSRV#1]
Проверьте исходный текст клиента
https://github.com/Gibadullina-Darina/OSRV/blob/bbb3269db49a58e1f7d8b37bfb49f46067484813/LaboratornayaRabota3/client.c#L18

**Comment by Gibadullina-Darina** [comment]
Перепроверила. Немного запуталась и начала писать код с листочка клиента.

**Comment by Gibadullina-Darina** [comment]
Перепроверила. Немного запуталась и начала писать код с листочка сервера
